Repository vehicle-lang/vehicle, pull requests merged in 2022-11, with the labels that each got.

#226 Renamed Meta to MetaID
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Normalise/NormExpr.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Core.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Compile/Type/MetaMap.hs
  vehicle/src/Vehicle/Compile/Type/MetaSet.hs
  vehicle/src/Vehicle/Compile/Type/Monad.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Language/AST/CoDeBruijn.hs
  vehicle/src/Vehicle/Language/AST/Expr.hs
  vehicle/src/Vehicle/Language/AST/Meta.hs
  vehicle/src/Vehicle/Language/Print.hs
Labels: refactoring, compiler:type-checker

#227 Split up type-checking monad into separate Class and Instance files
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Compile/Type/Monad.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
  vehicle/src/Vehicle/Compile/Type/VariableContext.hs
  vehicle/vehicle.cabal
Labels: refactoring, compiler:type-checker

#229 Refactor constraint types using new WithContext type family
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Core.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Linearity.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Polarity.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
  vehicle/src/Vehicle/Language/Print.hs
Labels: refactoring, compiler:type-checker

#231 Improve constraint error messages
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Auxiliary.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Resource.hs
  vehicle/tests/golden/error/typing/incorrectTensorLength/TypeCheck.err.golden
  vehicle/tests/golden/error/typing/incorrectTensorLength/TypeCheck.out.golden
  vehicle/tests/golden/error/typing/unsolvedMeta/TypeCheck.err.golden
  vehicle/tests/golden/error/typing/unsolvedMeta/TypeCheck.out.golden
Labels: enhancement, compiler:type-checker

#233 Removed unnecessary lifting of meta-variable solutions in meta-variable substitution
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Linearity.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Polarity.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
Labels: refactoring, compiler:type-checker

#236 Use NBE when solving unification constraints
  vehicle/src/Vehicle/Compile/Elaborate/External.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Normalise/NormExpr.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Prelude/Utils.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Auxiliary.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Core.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Linearity.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Polarity.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Compile/Type/MetaMap.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/VariableContext.hs
  vehicle/src/Vehicle/Language/AST/DeBruijn.hs
  vehicle/src/Vehicle/Language/AST/Expr.hs
  vehicle/src/Vehicle/Language/Print.hs
  vehicle/tests/golden/compile/acasXu/acasXu.agda.golden
  vehicle/tests/golden/compile/autoencoderError/autoencoderError.agda.golden
  vehicle/tests/golden/compile/mnist-robustness/mnist-robustness.agda.golden
  vehicle/tests/golden/compile/reachability/reachability.agda.golden
  vehicle/tests/golden/compile/windController/windController.agda.golden
  vehicle/tests/unit/Tests.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/DeBruijn.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/Normalisation.hs
  vehicle/vehicle.cabal
Labels: refactoring, compiler:type-checker

#237 Push NBE through type-class constraints
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Normalise/NormExpr.hs
  vehicle/src/Vehicle/Compile/Prelude/Utils.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Core.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Linearity.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Polarity.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Language/Print.hs
Labels: refactoring, compiler:type-checker

#238 Pushed use of NBE through resource type-checking
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/Elaborate/External.hs
  vehicle/src/Vehicle/Compile/Elaborate/Internal.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/ExpandResources.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Core.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Dataset.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Dataset/IDX.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Network.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Parameter.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Normalise/NormExpr.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Resource.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Irrelevance.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Compile/Type/Resource.hs
  vehicle/src/Vehicle/Compile/Type/VariableContext.hs
  vehicle/src/Vehicle/Language/AST/Arg.hs
  vehicle/src/Vehicle/Language/AST/Decl.hs
  vehicle/src/Vehicle/Prelude/Logging.hs
  vehicle/src/Vehicle/Prelude/Misc.hs
  vehicle/src/Vehicle/Resource.hs
  vehicle/tests/golden/error/dataset/invalidContainerType/TypeCheck.err.golden
  vehicle/tests/golden/error/dataset/invalidContainerType/TypeCheck.out.golden
  vehicle/tests/golden/error/dataset/invalidElementType/TypeCheck.err.golden
  vehicle/tests/golden/error/dataset/invalidElementType/TypeCheck.out.golden
  vehicle/tests/golden/error/dataset/variableDimensions/Marabou.err.golden
  vehicle/tests/golden/error/dataset/variableDimensions/Marabou.out.golden
  vehicle/tests/golden/error/network/notAFunction/TypeCheck.err.golden
  vehicle/tests/golden/error/network/notAFunction/TypeCheck.out.golden
  vehicle/tests/golden/error/parameter/unsupportedType/Marabou.err.golden
  vehicle/tests/golden/error/parameter/unsupportedType/Marabou.out.golden
Labels: enhancement, compiler:type-checker, errors-and-warnings

#239 Fixes #213 by removing rogue printFriendly with no bound context
  vehicle/src/Vehicle/Compile/Queries/LNF.hs
  vehicle/tests/golden/compile/bounded/Marabou.err.golden
  vehicle/tests/golden/compile/bounded/Marabou.out.golden
  vehicle/tests/golden/compile/bounded/bounded.inputquery/bounded-query1.txt.golden
  vehicle/tests/golden/compile/bounded/bounded.inputquery/bounded-query2.txt.golden
  vehicle/tests/golden/compile/bounded/test.json
Labels: bug, backend:Marabou

#242 Fix #240 by switching let-expressions to use argument inference
  ChangeLog.md
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Language/Print.hs
  vehicle/tests/golden/Vehicle/Test/Golden.hs
  vehicle/tests/golden/compile/simple-let/simple-let.agda.golden
  vehicle/tests/golden/compile/simple-let/simple-let.vcl
Labels: bug, compiler:type-checker

#243 Reorganise meta-variable code in type-checker to make it more modular
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Auxiliary.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Core.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Linearity.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Polarity.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Map.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Set.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
  vehicle/src/Vehicle/Language/AST/Meta.hs
  vehicle/src/Vehicle/Language/Print.hs
  vehicle/vehicle.cabal
Labels: refactoring, compiler:type-checker

#244 Speedup type-checking slightly by removing unneccessary meta substitution through meta-types
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Map.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
Labels: refactoring, compiler:type-checker, performance

#248 Fix #246 by improving the error message for invalid property types
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Language/AST.hs
  vehicle/src/Vehicle/Language/AST/Decl.hs
  vehicle/tests/golden/error/dataset/invalidContainerType/TypeCheck.err.golden
  vehicle/tests/golden/error/dataset/invalidElementType/TypeCheck.err.golden
  vehicle/tests/golden/error/dataset/variableDimensions/Marabou.err.golden
  vehicle/tests/golden/error/network/notAFunction/TypeCheck.err.golden
  vehicle/tests/golden/error/parameter/unsupportedType/Marabou.err.golden
  vehicle/tests/golden/error/property/invalidType/TypeCheck.err.golden
  vehicle/tests/golden/error/property/invalidType/TypeCheck.out.golden
Labels: enhancement, errors-and-warnings

#250 Stop substituting metas through all constraints every pass
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
Labels: refactoring, compiler:type-checker, performance

#251 Improve type-checking performance by removing substitutions through meta solutions
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
Labels: compiler:type-checker, performance

#252 Improve performance of type-checking by better guards for logging
  vehicle/src/Vehicle/Compile/Type.hs
Labels: compiler:type-checker, performance

#254 Python commandline3
  vehicle-python/src/vehicle/bounded-output.json
  vehicle-python/src/vehicle/command_line.py
  vehicle-python/src/vehicle/t.json
  vehicle-python/src/vehicle/test.py
  vehicle-python/src/vehicle/test_LossFunctionTranslation.py
  vehicle-python/src/vehicle/test_json/test_addition.vcl
  vehicle-python/src/vehicle/test_json/test_at.json
  vehicle-python/src/vehicle/test_json/test_at.vcl
  vehicle-python/src/vehicle/test_json/test_constant.json
  vehicle-python/src/vehicle/test_json/test_constant.vcl
  vehicle-python/src/vehicle/test_json/test_division.vcl
  vehicle-python/src/vehicle/test_json/test_domain.json
  vehicle-python/src/vehicle/test_json/test_indicator.json
  vehicle-python/src/vehicle/test_json/test_indicator.vcl
  vehicle-python/src/vehicle/test_json/test_lambda.json
  vehicle-python/src/vehicle/test_json/test_maximum.json
  vehicle-python/src/vehicle/test_json/test_maximum.vcl
  vehicle-python/src/vehicle/test_json/test_minimum.vcl
  vehicle-python/src/vehicle/test_json/test_multiplication.vcl
  vehicle-python/src/vehicle/test_json/test_negation.json
  vehicle-python/src/vehicle/test_json/test_negation.vcl
  vehicle-python/src/vehicle/test_json/test_network.json
  vehicle-python/src/vehicle/test_json/test_network.vcl
  vehicle-python/src/vehicle/test_json/test_quantifier.json
  vehicle-python/src/vehicle/test_json/test_quantifier_all.vcl
  vehicle-python/src/vehicle/test_json/test_quantifier_any.vcl
  vehicle-python/src/vehicle/test_json/test_subtraction.json
  vehicle-python/src/vehicle/test_json/test_subtraction.vcl
  vehicle-python/src/vehicle/test_json/test_tensor.json
  vehicle-python/src/vehicle/test_json/test_tensor.vcl
  vehicle-python/src/vehicle/test_json/test_variable.json
  vehicle-python/src/vehicle/test_json/test_variable.vcl
  vehicle-python/src/vehicle/vehicle.py
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/tests/golden/compile/andGate/test.json
  vehicle/tests/golden/compile/simple-quantifier/test.json
  vehicle/tests/golden/compile/simple-vector/LossFunction.err.golden
  vehicle/tests/golden/compile/simple-vector/LossFunction.out.golden
  vehicle/tests/golden/compile/simple-vector/simple-vector.loss.json.golden
  vehicle/tests/golden/compile/windController/test.json
Labels: enhancement, backend:LossFunctions

#256 Fix dependabot for readthedocs
  .github/dependabot.yml
Labels: bug, build-system

#258 Removed another unused normalisation option
  .gitignore
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
Labels: refactoring, compiler:normalisation

#259 Fixes #253 #230 by improving setup documentation
  HACKING.md
  docs-source/installation.rst
Labels: bug, documentation

#261 Fix #220 by documenting what happens when no proof cache is provided when exporting to Agda
  docs-source/theorem-proving.rst
Labels: documentation, enhancement, backend:Agda

#255 Steps towards packaging vehicle-python
  .github/actions/setup-poetry/action.yml
  .github/actions/setup-vehicle/action.yml
  .github/dependabot.yml
  .github/workflows/build-vehicle-python.yml
  .github/workflows/build-vehicle.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-editor-integration.yml
  .pre-commit-config.yaml
  HACKING.md
  README.md
  docs-source/conf.py
  tools/idx/makeIDX.py
  tools/idx/shrinkIDX.py
  tools/networks/train-networks.py
  vehicle-python/.gitignore
  vehicle-python/.python-version
  vehicle-python/README.md
  vehicle-python/poetry.lock
  vehicle-python/pyproject.toml
  vehicle-python/src/vehicle/command_line.py
  vehicle-python/src/vehicle/utils.py
  vehicle-python/tests/bounded-output.json
  vehicle-python/tests/bounded.vcl
  vehicle-python/tests/data/test_addition.json
  vehicle-python/tests/data/test_addition.vcl
  vehicle-python/tests/data/test_at.json
  vehicle-python/tests/data/test_at.vcl
  vehicle-python/tests/data/test_constant.json
  vehicle-python/tests/data/test_constant.vcl
  vehicle-python/tests/data/test_division.json
  vehicle-python/tests/data/test_division.vcl
  vehicle-python/tests/data/test_indicator.vcl
  vehicle-python/tests/data/test_maximum.json
  vehicle-python/tests/data/test_maximum.vcl
  vehicle-python/tests/data/test_minimum.json
  vehicle-python/tests/data/test_minimum.vcl
  vehicle-python/tests/data/test_multiplication.json
  vehicle-python/tests/data/test_multiplication.vcl
  vehicle-python/tests/data/test_negation.json
  vehicle-python/tests/data/test_negation.vcl
  vehicle-python/tests/data/test_network.json
  vehicle-python/tests/data/test_network.vcl
  vehicle-python/tests/data/test_quantifier_all.json
  vehicle-python/tests/data/test_quantifier_all.vcl
  vehicle-python/tests/data/test_quantifier_any.json
  vehicle-python/tests/data/test_quantifier_any.vcl
  vehicle-python/tests/data/test_subtraction.json
  vehicle-python/tests/data/test_subtraction.vcl
  vehicle-python/tests/data/test_tensor.json
  vehicle-python/tests/data/test_tensor.vcl
  vehicle-python/tests/data/test_variable.json
  vehicle-python/tests/data/test_variable.vcl
  vehicle-python/tests/t.json
  vehicle-python/tests/test.py
  vehicle-python/tests/test_LossFunctionTranslation.py
  vehicle-python/vehicle/__init__.py
  vehicle-python/vehicle/command_line.py
  vehicle-python/vehicle/utils.py
Labels: enhancement, backend:LossFunctions, build-system

#266 Support for GHC 9.2
  .github/workflows/build.yml
  cabal.project.ghc-9.2
  cabal.project.ghc-9.2.freeze
  vehicle-syntax/vehicle-syntax.cabal
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/vehicle.cabal
Labels: enhancement, build-system

#264 Improve documentation - fixing bugs and adding detail
  docs-source/language/arithmetic.rst
  docs-source/language/datasets.rst
  docs-source/language/functions.rst
  docs-source/language/lists.rst
  docs-source/language/logic.rst
  docs-source/language/networks.rst
  docs-source/language/parameters.rst
  docs-source/language/properties.rst
  docs-source/language/quantifiers.rst
  docs-source/language/tensors.rst
  docs-source/language/vectors.rst
Labels: documentation, enhancement

#271 Support Python 3.9
  .github/workflows/build.yml
Labels: enhancement, build-system

#279 Set fail-fast: true
  .github/workflows/build.yml
Labels: build-system

#275 Support Python 3.8
  .github/workflows/build.yml
  vehicle-python/pyproject.toml
  vehicle-python/vehicle/__init__.py
  vehicle-python/vehicle/command_line.py
  vehicle-python/vehicle/utils.py
Labels: build-system, mypy

#276 Support Python 3.7
  .github/workflows/build.yml
  vehicle-python/pyproject.toml
Labels: build-system, mypy

#290 Network variable names refactor
  vehicle/src/Vehicle/Compile/Linearity.hs
  vehicle/src/Vehicle/Compile/Monomorphisation.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Queries.hs
  vehicle/src/Vehicle/Compile/Queries/FourierMotzkinElimination.hs
  vehicle/src/Vehicle/Compile/Queries/GaussianElimination.hs
  vehicle/src/Vehicle/Compile/Queries/LinearExpr.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Compile/Queries/Variable.hs
  vehicle/src/Vehicle/Compile/Queries/VariableReconstruction.hs
  vehicle/src/Vehicle/Compile/Resource.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Irrelevance.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Expr/DeBruijn.hs
  vehicle/src/Vehicle/Verify/Verifier/Interface.hs
  vehicle/src/Vehicle/Verify/Verifier/Marabou.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/DeBruijn.hs
  vehicle/vehicle.cabal
Labels: backend:Marabou, refactoring

#292 Added (very basic) module information to identifiers
  vehicle-syntax/src/Vehicle/Syntax/AST/Name.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/Parse.hs
  vehicle-syntax/vehicle-syntax.cabal
  vehicle/src/Vehicle/Compile/CapitaliseTypeNames.hs
  vehicle/src/Vehicle/Compile/Dependency/Analysis.hs
  vehicle/src/Vehicle/Compile/Descope.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Monomorphisation.hs
  vehicle/src/Vehicle/Compile/Queries.hs
  vehicle/src/Vehicle/Compile/Scope.hs
  vehicle/src/Vehicle/Language/StandardLibrary.hs
  vehicle/src/Vehicle/Language/StandardLibrary/Names.hs
  vehicle/src/Vehicle/Verify/Specification.hs
  vehicle/src/Vehicle/Verify/Specification/IO.hs
  vehicle/src/Vehicle/Verify/Specification/Status.hs
Labels: enhancement

#296 Remove ability to redirect stdout and stderr
  vehicle/src/Vehicle.hs
  vehicle/src/Vehicle/Check.hs
  vehicle/src/Vehicle/CommandLine.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Export.hs
  vehicle/src/Vehicle/Prelude/IO.hs
  vehicle/src/Vehicle/Verify.hs
  vehicle/src/Vehicle/Verify/Specification/IO.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/CommandLine.hs
Labels: refactoring, errors-and-warnings

#298 Fix #294 by introducing the concept of different logging backends
  ChangeLog.md
  vehicle/src/Vehicle.hs
  vehicle/src/Vehicle/Check.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/ExpandResources.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Prelude/IO.hs
  vehicle/src/Vehicle/Prelude/Logging.hs
  vehicle/src/Vehicle/Prelude/Logging/Backend.hs
  vehicle/src/Vehicle/Prelude/Logging/Class.hs
  vehicle/src/Vehicle/Prelude/Logging/Instance.hs
  vehicle/src/Vehicle/Verify.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Common.hs
  vehicle/vehicle.cabal
Labels: refactoring, errors-and-warnings
