Repository vehicle-lang/vehicle, pull requests merged in 2022-12, with the labels that each got.

#299 Add interface files to Vehicle
  .gitignore
  ChangeLog.md
  vehicle-syntax/src/Vehicle/Syntax/AST/Arg.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Binder.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/Core.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/Linearity.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/Polarity.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/TypeClass.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Decl.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Meta.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Prog.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Provenance.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Relevance.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Visibility.hs
  vehicle/src/Vehicle/Backend/Agda/Interact.hs
  vehicle/src/Vehicle/Backend/LossFunction/Interact.hs
  vehicle/src/Vehicle/Backend/Prelude.hs
  vehicle/src/Vehicle/CommandLine.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/ObjectFile.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Export.hs
  vehicle/src/Vehicle/Expr/DeBruijn.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/Prelude/IO.hs
  vehicle/src/Vehicle/Resource.hs
  vehicle/src/Vehicle/Verify.hs
  vehicle/src/Vehicle/Verify/ProofCache.hs
  vehicle/src/Vehicle/Verify/Specification/IO.hs
  vehicle/tests/golden/Vehicle/Test/Golden.hs
  vehicle/tests/golden/error/argument/missingInputFile/TypeCheck.err.golden
  vehicle/tests/golden/error/argument/wrongFileExtension/TypeCheck.err.golden
  vehicle/tests/golden/error/argument/wrongFileExtension/TypeCheck.out.golden
  vehicle/tests/golden/error/argument/wrongFileExtension/test.json
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/CommandLine.hs
  vehicle/vehicle.cabal
Labels: enhancement, compiler:type-checker

#304 Simplify provenance implementation and remove dependency on range package
  vehicle-syntax/src/Vehicle/Syntax/AST/Provenance.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/Internal.hs
  vehicle-syntax/vehicle-syntax.cabal
Labels: refactoring, compiler:error-messages

#306 Remove the concept of property context
  vehicle-syntax/src/Vehicle/Syntax/AST/Decl.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/Parse.hs
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/CapitaliseTypeNames.hs
  vehicle/src/Vehicle/Compile/Dependency/Analysis.hs
  vehicle/src/Vehicle/Compile/ExpandResources.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Core.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Dataset/IDX.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Network.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Parameter.hs
  vehicle/src/Vehicle/Compile/Monomorphisation.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/ObjectFile.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Queries.hs
  vehicle/src/Vehicle/Compile/Resource.hs
  vehicle/src/Vehicle/Compile/Scope.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Auxiliary.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Irrelevance.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Output.hs
  vehicle/src/Vehicle/Compile/Type/VariableContext.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/Prelude/IO.hs
  vehicle/src/Vehicle/Resource.hs
  vehicle/vehicle.cabal
Labels: refactoring, compiler:type-checker

#308 Load empty standard library
  ChangeLog.md
  vehicle-python/pyproject.toml
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/CommandLine.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/ExpandResources.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Core.hs
  vehicle/src/Vehicle/Compile/ObjectFile.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Queries.hs
  vehicle/src/Vehicle/Compile/Scope.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
  vehicle/src/Vehicle/Compile/Type/Output.hs
  vehicle/src/Vehicle/Compile/Type/VariableContext.hs
  vehicle/src/Vehicle/Export.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/Language/StandardLibrary.hs
  vehicle/src/Vehicle/Prelude/IO.hs
  vehicle/src/Vehicle/Prelude/Logging/Backend.hs
  vehicle/src/Vehicle/Verify.hs
  vehicle/src/Vehicle/Verify/ProofCache.hs
  vehicle/tests/golden/Vehicle/Test/Golden.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Common.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/LetInsertion.hs
  vehicle/vehicle.cabal
Labels: enhancement

#317 Fix #156 where higher-order functions wouldn't type-check
  ChangeLog.md
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/tests/golden/compile/simple-higherOrder/simple-higherOrder.vcl
  vehicle/tests/golden/compile/simple-higherOrder/test.json
Labels: bug

#319 Add library versioning and include imports at normalisation time
  vehicle-syntax/src/Vehicle/Syntax/AST/Arg.hs
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Expr/Patterns.hs
  vehicle/src/Vehicle/Language/StandardLibrary.hs
  vehicle/src/Vehicle/Libraries.hs
  vehicle/src/Vehicle/Libraries/StandardLibrary.hs
  vehicle/src/Vehicle/Libraries/StandardLibrary/Names.hs
  vehicle/src/Vehicle/Prelude/IO.hs
  vehicle/src/Vehicle/Prelude/Logging/Class.hs
  vehicle/tests/golden/compile/stdlib/TypeCheck.err.golden
  vehicle/tests/golden/compile/stdlib/TypeCheck.out.golden
  vehicle/tests/golden/compile/stdlib/stdlib.vcl
  vehicle/tests/golden/compile/stdlib/test.json
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/LetInsertion.hs
  vehicle/vehicle.cabal
Labels: enhancement

#320 Fix generalisation bug in scope checker and use stdlib function in normalisation
  ChangeLog.md
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle-syntax/src/Vehicle/Syntax/Parse.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Normalise/Core.hs
  vehicle/src/Vehicle/Compile/Scope.hs
  vehicle/src/Vehicle/Libraries/StandardLibrary.hs
  vehicle/tests/golden/compile/stdlib/stdlib.vcl
Labels: bug, compiler:other

#323 Fix various problems with folds in type-checking and normalisation
  ChangeLog.md
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/External.cf
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Normalise/Core.hs
  vehicle/src/Vehicle/Compile/Type/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Libraries/StandardLibrary.hs
  vehicle/tests/golden/compile/autoencoderError/autoencoderError.test.json
  vehicle/tests/golden/compile/stdlib/stdlib.vcl
Labels: bug, compiler:type-checker, compiler:normalisation

#327 Fix CI: remove Tox, run Python 3.8.0 on Ubuntu 20.04
  .github/actions/setup-poetry/action.yml
  .github/actions/setup-python/action.yml
  .github/workflows/build-vehicle-python.yml
  .github/workflows/build.yml
  vehicle-python/.python-version
  vehicle-python/poetry.lock
  vehicle-python/pyproject.toml
Labels: build-system

#328 Turn DB indices into a newtype
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Backend/LossFunction/Logics.hs
  vehicle/src/Vehicle/Compile/Descope.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Network.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Prelude/Contexts.hs
  vehicle/src/Vehicle/Compile/Prelude/Utils.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Compile/Scope.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn/Conversion.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn/PositionTree.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/DeBruijn.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/Expr/Patterns.hs
Labels: refactoring, compiler:other

#332 Add `HasMap` type class
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/TypeClass.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Relevance.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Type/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/tests/golden/compile/simple-map/simple-map.vcl
  vehicle/tests/golden/compile/simple-map/test.json
Labels: enhancement, compiler:type-checker

#335 Migrate strictness annotations to use of StrictData and add benchmarks
  scripts/benchmark
  vehicle-syntax/src/Vehicle/Syntax/AST.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Arg.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Binder.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/Core.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/Linearity.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/Polarity.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/TypeClass.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Decl.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Instances/NoThunks.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Meta.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Name.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Prog.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Provenance.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Relevance.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Visibility.hs
  vehicle-syntax/vehicle-syntax.cabal
Labels: refactoring

#346 Fix performance problems by temporarily changing cabal library used for executable component
  .github/workflows/build.yml
  vehicle/vehicle.cabal
Labels: performance

#347 Remove `SupplyNames` compiler pass
  vehicle-syntax/src/Vehicle/Syntax/AST/Binder.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Name.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/Print.hs
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Compile/Descope.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/LetInsertion.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Prelude/Contexts.hs
  vehicle/src/Vehicle/Compile/Prelude/Utils.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Compile/Scope.hs
  vehicle/src/Vehicle/Compile/SupplyNames.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
  vehicle/src/Vehicle/Compile/Type/Resource.hs
  vehicle/src/Vehicle/Compile/Type/VariableContext.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn/Conversion.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/DeBruijn.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/DeBruijn.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/LetInsertion.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/Normalisation.hs
  vehicle/vehicle.cabal
Labels: refactoring, compiler:other
