Repository vehicle-lang/vehicle, pull requests merged in 2023-03, with the labels that each got.

#433 Add type class for linear expressions and add sparse linear expression representation
  vehicle/src/Vehicle/Compile/Queries/FourierMotzkinElimination.hs
  vehicle/src/Vehicle/Compile/Queries/GaussianElimination.hs
  vehicle/src/Vehicle/Compile/Queries/LinearExpr.hs
  vehicle/src/Vehicle/Compile/Queries/LinearSatisfactionProblem.hs
  vehicle/src/Vehicle/Compile/Queries/VariableReconstruction.hs
  vehicle/src/Vehicle/Verify/Specification.hs
  vehicle/src/Vehicle/Verify/Verifier/Marabou.hs
  vehicle/tests/golden/compile/acasXu/acasXu.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/andGate/andGate.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/autoencoderError/autoencoderError.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/bounded/bounded.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/increasing/increasing.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/monotonicity/monotonicity.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/quantifierInIf/quantifierInIf.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/reachability/reachability.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/simple-constantInput/simple-constantInput.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/simple-fourierMotzkin/simple-fourierMotzkin.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/simple-gaussianElim/simple-gaussianElim.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/simple-if/simple-if.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/simple-pruneDecls/simple-pruneDecls.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/simple-quantifier/simple-quantifier.inputquery/verification-plan.vcle.golden
  vehicle/tests/golden/compile/windController/windController.inputquery/verification-plan.vcle.golden
Labels: backend:Marabou, refactoring, performance

#442 Remove obsolete normalisation code
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/vehicle.cabal
Labels: refactoring, compiler:normalisation

#441 Remove CoDeBrujin indices and alpha equivalence
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Monomorphisation.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Expr/AlphaEquivalence.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn/Conversion.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn/PositionTree.hs
  vehicle/src/Vehicle/Expr/Hashing.hs
  vehicle/tests/unit/Tests.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/AlphaEquivalence.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/CoDeBruijn.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/DeBruijn.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/Normalisation.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/PositionTree.hs
  vehicle/vehicle.cabal
Labels: refactoring

#440 Document profiling scripts
  HACKING.md
  scripts/vehicle-profile-heap
  scripts/vehicle-profile-time
Labels: documentation, build-system

#450 Remove unneeded import
  vehicle/src/Vehicle/Compile/Queries/LinearSatisfactionProblem.hs
Labels: bug

#455 Fix bug introduced in golden testing code in previous commit
  vehicle/tests/golden/Vehicle/Test/Golden/TestSpec.hs
Labels: bug, test-suite

#457 Update ACAS Xu spec to include normalisation and fix bugs in LNF code
  ChangeLog.md
  examples/acasXu/acasXu.vcl
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Queries/LNF.hs
  vehicle/src/Vehicle/Compile/Queries/LinearSatisfactionProblem.hs
  vehicle/src/Vehicle/Compile/Queries/LinearityAndPolarityErrors.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/tests/golden/Vehicle/Test/Golden/TestSpec.hs
  vehicle/tests/golden/compile/acasXu/Agda.agda.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property1-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property10-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property10-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property10-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property10-query4.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property2-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property3-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property4-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property5-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property5-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property5-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property5-query4.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query4.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query5.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query6.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query7.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query8.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property7-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property7-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query10.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query11.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query12.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query13.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query14.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query15.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query16.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query4.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query5.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query6.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query7.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query8.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query9.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property9-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property9-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property9-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property9-query4.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/verification-plan.vcle.golden
Labels: bug, backend:Marabou, test-suite

#459 Fix `alex` version
  vehicle-syntax/vehicle-syntax.cabal
Labels: bug, CI

#461 Add (untested) VNNLib support
  vehicle/src/Vehicle/Compile/Queries/LinearExpr.hs
  vehicle/src/Vehicle/Verify/Core.hs
  vehicle/src/Vehicle/Verify/QueryFormat/Marabou.hs
  vehicle/src/Vehicle/Verify/QueryFormat/VNNLib.hs
  vehicle/src/Vehicle/Verify/Verifier.hs
  vehicle/src/Vehicle/Verify/Verifier/Marabou.hs
  vehicle/vehicle.cabal
Labels: enhancement, backend:Marabou

#470 Added progress bars and fixed wind-controller example
  ChangeLog.md
  examples/windController/controller.onnx
  vehicle/src/Vehicle/Expr/Boolean.hs
  vehicle/src/Vehicle/Verify/Specification.hs
  vehicle/src/Vehicle/Verify/Specification/IO.hs
  vehicle/vehicle.cabal
Labels: bug, enhancement, upstream, UX

#463 Loss experiments
  examples/mnist-robustness-loss-functions/README.md
  examples/mnist-robustness-loss-functions/mnist.vcl
  examples/mnist-robustness-loss-functions/mnist_constraint_accuracy.py
  examples/mnist-robustness-loss-functions/test_mnist_custom_loss.py
  vehicle-python/benchmarks.sh
  vehicle-python/tests/test_LossFunctionTranslation.py
  vehicle-python/tests/test_bounded.py
  vehicle-python/vehicle/__init__.py
  vehicle-python/vehicle/command_line.py
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Backend/LossFunction/Logics.hs
  vehicle/src/Vehicle/Backend/Prelude.hs
  vehicle/tests/golden/compile/andGate/LossFunction.json.golden
  vehicle/tests/golden/compile/bounded/LossFunction.json.golden
  vehicle/tests/golden/compile/logic-and-comparisons/LossFunction-Godel.json.golden
  vehicle/tests/golden/compile/logic-and-comparisons/LossFunction-Lukasiewicz.json.golden
  vehicle/tests/golden/compile/logic-and-comparisons/LossFunction-Product.json.golden
  vehicle/tests/golden/compile/logic-and-comparisons/LossFunction-Yager.json.golden
  vehicle/tests/golden/compile/monotonicity/LossFunction.json.golden
Labels: bug, backend:LossFunctions, python
