Repository vehicle-lang/vehicle, pull requests merged in 2023-05, with the labels that each got.

#521 Preparations for implementing @noinline in NBE
  vehicle-syntax/src/Vehicle/Syntax/AST/Decl.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Instances/NoThunks.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Name.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Utils.hs
  vehicle-syntax/src/Vehicle/Syntax/External.cf
  vehicle/lib/std.vcl
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/ExpandResources.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Core.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Dataset/IDX.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Network.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Parameter.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Queries.hs
  vehicle/src/Vehicle/Compile/Resource.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Core.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Linearity.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Polarity.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/AnnotationRestrictions.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Core.hs
  vehicle/src/Vehicle/Resource.hs
  vehicle/tests/golden/error/inferableParameter/unsupportedType/TypeCheck.err.golden
Labels: refactoring, compiler:normalisation

#526 Replace `normApp` with smart `App` synonym
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/Internal.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/DeBruijn.hs
Labels: refactoring

#539 Improve multi-network application error messages
  .gitignore
  ChangeLog.md
  vehicle/src/Vehicle/Prelude/Misc.hs
  vehicle/src/Vehicle/Verify/Verifier/Marabou.hs
Labels: enhancement, errors-and-warnings

#528 Update installation docs with latest information
  HACKING.md
  README.md
  docs-source/installation.rst
  docs-source/language/arithmetic.rst
  docs-source/language/quantifiers.rst
Labels: documentation, enhancement

#540 Fixed bug bug in default type arguments for Index literals
  ChangeLog.md
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Core.hs
  vehicle/tests/golden/compile/simple-defaultTypes/spec.vcl
  vehicle/tests/golden/compile/simple-defaultTypes/test.json
Labels: bug, compiler:type-checker

#543 Updated Vehicle agda library to work with 2.6.2 and fixed bugs in docs
  docs-source/exportingToITP.rst
  examples/windController/README.md
  examples/windController/agdaProof/windController.agda-lib
  vehicle-agda/src/Vehicle.agda
  vehicle-agda/src/Vehicle/Utils.agda
  vehicle-agda/vehicle.agda-lib
Labels: bug, documentation, backend:Agda

#552 Fix #551 Handle trivial cases in linear expression compilation
  ChangeLog.md
  vehicle/src/Vehicle/Compile/Queries/LinearSatisfactionProblem.hs
  vehicle/src/Vehicle/Expr/Boolean.hs
  vehicle/tests/golden/compile/issue551/Marabou.err.golden
  vehicle/tests/golden/compile/issue551/Marabou.out.golden
  vehicle/tests/golden/compile/issue551/Marabou.queries/.vcl-plan.golden
  vehicle/tests/golden/compile/issue551/Marabou.queries/robustAround-query1.txt.golden
  vehicle/tests/golden/compile/issue551/fake.onnx
  vehicle/tests/golden/compile/issue551/spec.vcl
  vehicle/tests/golden/compile/issue551/test.json
Labels: bug, backend:Marabou
