Repository vehicle-lang/vehicle, pull requests merged in 2023-01, with the labels that each got.

#350 Switch from `DBIndex` to `DBLevel` for `NormExpr`s
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/Descope.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/ExpandResources.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Dataset/IDX.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Network.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Parameter.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Queries/QuantifierLifting.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Core.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Irrelevance.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Resource.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn/PositionTree.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/DeBruijn.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/DeBruijn.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/Normalisation.hs
Labels: refactoring, compiler:normalisation

#353 Add `Tensor` as a derived function in the standard library
  ChangeLog.md
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Name.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Utils.hs
  vehicle-syntax/src/Vehicle/Syntax/External.cf
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Compile/Descope.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/ExpandResources.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Prelude/Utils.hs
  vehicle/src/Vehicle/Compile/Scope.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Core.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/VariableContext.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/Expr/Patterns.hs
  vehicle/src/Vehicle/Libraries/StandardLibrary.hs
  vehicle/tests/golden/compile/simple-map/test.json
  vehicle/tests/golden/error/typing/intAsNat/TypeCheck.err.golden
  vehicle/tests/golden/error/typing/intAsNat/TypeCheck.out.golden
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/CoDeBruijn.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/Normalisation.hs
Labels: refactoring, language, compiler:type-checker, compiler:normalisation

#354 Refactoring of unification while trying to get `map` to work
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Core.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/tests/golden/compile/simple-map/simple-map.vcl
Labels: refactoring, compiler:type-checker

#355 Separate storage of `TypeClass` and `Unification` constraints
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Auxiliary.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Monad.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
  vehicle/src/Vehicle/Compile/Type/Resource.hs
Labels: refactoring, compiler:type-checker

#357 Added existing drafts in Documentation section
  README.md
Labels: documentation

#356 Separate out unification and type-class solving into separate passes
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Core.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/TypeClass.hs
  vehicle/src/Vehicle/Compile/Type/ConstraintSolver/Unification.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
Labels: refactoring, compiler:type-checker

#358 Implemented basic instance search and got it working for `HasMap List`
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/Core.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/LinearitySolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/PolaritySolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/UnificationSolver.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Monad.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/tests/golden/compile/simple-map/test.json
  vehicle/vehicle.cabal
Labels: enhancement, compiler:type-checker

#359 Add HasMap instance for Vector
  ChangeLog.md
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/UnificationSolver.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Monad.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
  vehicle/src/Vehicle/Compile/Type/VariableContext.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/Prelude/Logging/Class.hs
  vehicle/src/Vehicle/Prelude/Logging/Instance.hs
  vehicle/tests/golden/compile/simple-map/simple-map.vcl
Labels: bug, compiler:type-checker

#360 Minor refactor to unification and meta variable contexts to aid debugging
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/Core.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/UnificationSolver.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/tests/golden/verify/simple-triviallyTrue/Marabou.out.golden
  vehicle/tests/golden/verify/simple-triviallyTrue/simple-triviallyTrue.vcl
  vehicle/tests/golden/verify/simple-triviallyTrue/test.json
Labels: refactoring, compiler:type-checker

#364 Store insertion status on `Visibility` instead of on `Provenance`
  vehicle-syntax/src/Vehicle/Syntax/AST/Arg.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Binder.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Instances/NoThunks.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Name.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Provenance.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Visibility.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Utils.hs
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Dataset/IDX.hs
  vehicle/src/Vehicle/Compile/LetInsertion.hs
  vehicle/src/Vehicle/Compile/Monomorphisation.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Normalise/Core.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Prelude/Utils.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Compile/Scope.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type/Auxiliary.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/Core.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Resource.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn/Conversion.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/Expr/Patterns.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/DeBruijn.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/Normalisation.hs
Labels: refactoring, compiler:error-messages

#365 Consistently call things of type provenance `p`
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Compile/CapitaliseTypeNames.hs
  vehicle/src/Vehicle/Compile/Descope.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/LetInsertion.hs
  vehicle/src/Vehicle/Compile/Prelude/Utils.hs
  vehicle/src/Vehicle/Compile/Queries/DNF.hs
  vehicle/src/Vehicle/Compile/Queries/IfElimination.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Compile/Resource.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn.hs
  vehicle/src/Vehicle/Expr/CoDeBruijn/Conversion.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/Patterns.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Common.hs
Labels: refactoring

#367 Refactor delaboration to print implicit and instance arguments when not simplifying
  vehicle-syntax/src/Vehicle/Syntax/AST/Visibility.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
Labels: refactoring

#368 Add recursive instance search and use to implement `HasAdd`
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Type/Auxiliary.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/Constraint.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/Core.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceBuiltins.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/Prelude/Logging/Instance.hs
  vehicle/vehicle.cabal
Labels: enhancement, compiler:type-checker

#369 Shift `hasNot` and `hasEq Eq` to instance search
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceBuiltins.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Expr/DSL.hs
Labels: refactoring, compiler:type-checker

#370 First use of type-classes in native Vehicle code
  vehicle-agda/src/Vehicle/Utils.agda
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Queries/IfElimination.hs
  vehicle/src/Vehicle/Compile/Type/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceBuiltins.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/Patterns.hs
  vehicle/src/Vehicle/Libraries/StandardLibrary.hs
  vehicle/tests/golden/compile/acasXu/acasXu.agda.golden
  vehicle/tests/golden/compile/autoencoderError/autoencoderError.agda.golden
  vehicle/tests/golden/compile/mnist-robustness/mnist-robustness.agda.golden
  vehicle/tests/golden/compile/simple-arithmetic/Agda.err.golden
  vehicle/tests/golden/compile/simple-arithmetic/Agda.out.golden
  vehicle/tests/golden/compile/simple-arithmetic/simple-arithmetic.agda.golden
  vehicle/tests/golden/compile/simple-let/simple-let.agda.golden
  vehicle/tests/golden/compile/simple-tensor/simple-tensor.agda.golden
  vehicle/tests/golden/compile/stdlib/stdlib.vcl
  vehicle/tests/golden/compile/windController/windController.agda.golden
Labels: enhancement, compiler:type-checker

#371 Switched to binary serialisation of object files
  vehicle-syntax/src/Vehicle/Syntax/AST/Arg.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Binder.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/Core.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/Linearity.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/Polarity.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/TypeClass.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Decl.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Meta.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Name.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Prog.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Provenance.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Relevance.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Visibility.hs
  vehicle-syntax/src/Vehicle/Syntax/Prelude.hs
  vehicle-syntax/vehicle-syntax.cabal
  vehicle/src/Vehicle/Compile/ObjectFile.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Expr/DeBruijn.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/Verify/Specification/IO.hs
  vehicle/src/Vehicle/Verify/Specification/Status.hs
  vehicle/vehicle.cabal
Labels: refactoring, performance

#372 Move more type classes to instance search
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/ExpandResources/Dataset/IDX.hs
  vehicle/src/Vehicle/Compile/LetInsertion.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Queries/DNF.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceBuiltins.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/tests/golden/compile/simple-untypedDecls/Agda.err.golden
  vehicle/tests/golden/compile/simple-untypedDecls/Agda.out.golden
  vehicle/tests/golden/compile/simple-untypedDecls/simple-untypedDecls.agda.golden
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/PositionTree.hs
Labels: refactoring

#373 Fixes #366 by catching error when referenced declaration doesn't exist
  vehicle/src/Vehicle/Compile/Dependency/Analysis.hs
  vehicle/src/Vehicle/Compile/Dependency/Graph.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/tests/golden/error/argument/missingDeclaration/TypeCheck.err.golden
  vehicle/tests/golden/error/argument/missingDeclaration/TypeCheck.out.golden
  vehicle/tests/golden/error/argument/missingDeclaration/missingDeclaration.vcl
  vehicle/tests/golden/error/argument/missingDeclaration/test.json
Labels: bug, compiler:error-messages

#374 Move index quantifiers to the standard library
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/Core.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/UnificationSolver.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Monad.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
  vehicle/src/Vehicle/Expr/Patterns.hs
  vehicle/src/Vehicle/Libraries/StandardLibrary.hs
  vehicle/src/Vehicle/Libraries/StandardLibrary/Names.hs
Labels: refactoring

#376 Add HasEq to user syntax and equalsVector to stdlib
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Utils.hs
  vehicle-syntax/src/Vehicle/Syntax/External.cf
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Compile/Normalise.hs
  vehicle/src/Vehicle/Compile/Type/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceBuiltins.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/src/Vehicle/Expr/Patterns.hs
  vehicle/src/Vehicle/Libraries/StandardLibrary.hs
  vehicle/tests/golden/compile/stdlib/TypeCheck.err.golden
  vehicle/tests/golden/compile/stdlib/TypeCheck.out.golden
  vehicle/tests/golden/compile/stdlib/stdlib.vcl
  vehicle/tests/golden/compile/stdlib/test.json
Labels: refactoring, compiler:type-checker

#377 Add postulates to user syntax
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Utils.hs
  vehicle-syntax/src/Vehicle/Syntax/External.cf
Labels: enhancement, language

#291 now all the tests work after merging with Natalia
  vehicle-python/README.md
  vehicle-python/poetry.lock
  vehicle-python/pyproject.toml
  vehicle-python/tests/data/test_indicator.vcl
  vehicle-python/tests/data/test_maximum.vcl
  vehicle-python/tests/data/test_minimum.vcl
  vehicle-python/tests/data/test_negation.vcl
  vehicle-python/tests/data/test_power.vcl
  vehicle-python/tests/t.json
  vehicle-python/tests/test.py
  vehicle-python/tests/test_LossFunctionTranslation.py
  vehicle-python/vehicle/__init__.py
  vehicle-python/vehicle/command_line.py
Labels: backend:LossFunctions, test-suite

#381 Move removal of quantifiers to before network application lifting
  vehicle/src/Vehicle/Compile/LetInsertion.hs
  vehicle/src/Vehicle/Compile/Queries.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Compile/Queries/QuantifierLifting.hs
  vehicle/src/Vehicle/Compile/Queries/Variable.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/LetInsertion.hs
Labels: backend:Marabou, refactoring

#382 Use a continuation passing to cut out the use of CSE
  vehicle/src/Vehicle/Compile/Queries.hs
  vehicle/src/Vehicle/Compile/Queries/LinearSatisfactionProblem.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/vehicle.cabal
Labels: backend:Marabou, refactoring

#383 Remove all common subexpression elimination code now that its redundant
  vehicle/src/Vehicle/Compile/LetInsertion.hs
  vehicle/src/Vehicle/Compile/Normalise/Core.hs
  vehicle/src/Vehicle/Compile/Queries/LinearExpr.hs
  vehicle/src/Vehicle/Compile/Queries/LinearSatisfactionProblem.hs
  vehicle/src/Vehicle/Compile/Queries/NetworkElimination.hs
  vehicle/tests/unit/Tests.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/LetInsertion.hs
  vehicle/vehicle.cabal
Labels: backend:Marabou, refactoring, compiler:normalisation

#401 Fix problems with compilation of declarations to loss functions
  vehicle-python/vehicle/__init__.py
  vehicle-python/vehicle/command_line.py
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Backend/LossFunction/Logics.hs
  vehicle/tests/golden/compile/andGate/andGate.loss.json.golden
  vehicle/tests/golden/compile/simple-pruneDecls/simple-pruneDecls.loss.json.golden
Labels: bug, backend:LossFunctions, compiler:other
