Repository vehicle-lang/vehicle, pull requests merged in 2023-08, with the labels that each got.

#657 Refactor python bindings & added docstrings
  ChangeLog.md
  vehicle-python/.python-version
  vehicle-python/src/vehicle_lang/__init__.py
  vehicle-python/src/vehicle_lang/_error.py
  vehicle-python/src/vehicle_lang/_target.py
  vehicle-python/src/vehicle_lang/ast/__init__.py
  vehicle-python/src/vehicle_lang/compile/__init__.py
  vehicle-python/src/vehicle_lang/compile/abc.py
  vehicle-python/src/vehicle_lang/compile/python.py
  vehicle-python/src/vehicle_lang/error.py
  vehicle-python/src/vehicle_lang/session.py
  vehicle-python/src/vehicle_lang/typing.py
  vehicle-python/src/vehicle_lang/verify/__init__.py
  vehicle-python/tests/test_lossdl2_exec.py
  vehicle-python/tests/test_lossdl2_exec_tf_bounded.py
  vehicle-python/tests/test_lossdl2_exec_tf_mnist_robustness.py
  vehicle-python/tests/test_lossdl2_load.py
  vehicle-python/tests/test_main.py
  vehicle-python/tests/test_python_exec.py
  vehicle-python/tests/test_python_load.py
Labels: enhancement, backend:LossFunctions

#658 Setup basic support for autodoc
  docs/conf.py
  docs/dev/building.md
  docs/dev/index.rst
  docs/dev/python/vehicle_lang.rst
  docs/dev/releasing.md
  docs/dev/verifiers.md
  docs/exporting.rst
  docs/index.rst
  docs/requirements.txt
  docs/type-checking.rst
  docs/verifying.rst
Labels: documentation, CI

#660 Fix bug with non-unit pivot coefficients in Gaussian elimination
  ChangeLog.md
  vehicle/src/Vehicle/Compile/Queries/GaussianElimination.hs
  vehicle/src/Vehicle/Compile/Queries/UserVariableElimination.hs
  vehicle/tests/golden/compile/issue649/Marabou.err.golden
  vehicle/tests/golden/compile/issue649/Marabou.out.golden
  vehicle/tests/golden/compile/issue649/Marabou.queries/.vcl-cache-index.golden
  vehicle/tests/golden/compile/issue649/Marabou.queries/robust-query1.txt.golden
  vehicle/tests/golden/compile/issue649/Marabou.queries/robust.vcl-plan.golden
  vehicle/tests/golden/compile/issue649/fake.onnx
  vehicle/tests/golden/compile/issue649/spec.vcl
  vehicle/tests/golden/compile/issue649/test.json
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!0-query1.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!0-query2.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!0-query3.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!0-query4.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!0-query5.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!0-query6.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!0-query7.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!0-query8.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!0-query9.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!1-query1.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!1-query2.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!1-query3.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!1-query4.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!1-query5.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!1-query6.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!1-query7.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!1-query8.txt.golden
  vehicle/tests/golden/compile/mnist-robustness/Marabou.queries/robust!1-query9.txt.golden
Labels: bug, backend:Marabou

#661 Generalise instance solver to work over any builtin type
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/Core.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Core.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Linearity/Core.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Linearity/LinearitySolver.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Polarity/Core.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Polarity/PolaritySolver.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/Core.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/InstanceBuiltins.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Core.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Type.hs
  vehicle/vehicle.cabal
Labels: refactoring, compiler:type-checker

#667 Fix verification progress bar display bug and update .gitignore file
  .gitignore
  ChangeLog.md
  examples/windController/agdaProof/WindControllerSpec.agda
  examples/windController/verificationResult/.vcl-cache-index
  examples/windController/verificationResult/safe-query1.txt
  examples/windController/verificationResult/safe-query2.txt
  examples/windController/verificationResult/safe.vcl-plan
  examples/windController/verificationResult/safe.vcl-result
  vehicle/src/Vehicle/Compile/Queries/LinearExpr.hs
  vehicle/src/Vehicle/Verify/Specification/IO.hs
Labels: bug, backend:Marabou

#670 Change Sample to Optimise
  vehicle-python/src/vehicle_lang/__init__.py
  vehicle-python/src/vehicle_lang/ast/__init__.py
  vehicle-python/src/vehicle_lang/compile/__init__.py
  vehicle-python/src/vehicle_lang/compile/abc.py
  vehicle-python/src/vehicle_lang/compile/python.py
  vehicle-python/src/vehicle_lang/typing.py
  vehicle-python/tests/test_lossdl2_exec.py
  vehicle-python/tests/test_lossdl2_exec_tf_bounded.py
  vehicle-python/tests/test_lossdl2_exec_tf_mnist_robustness.py
  vehicle-python/tests/test_lossdl2_load.py
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/Builtin.hs
  vehicle/src/Vehicle/Backend/JSON.hs
  vehicle/src/Vehicle/Backend/LossFunction/Compile.hs
  vehicle/src/Vehicle/Backend/LossFunction/Logics.hs
  vehicle/src/Vehicle/Compile/Normalise/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Linearity/Type.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Polarity/Type.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Type.hs
  vehicle/tests/golden/compile/andGate/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/bounded/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/logic-and-comparisons/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/logic-and-comparisons/GodelLoss.vcl.golden
  vehicle/tests/golden/compile/logic-and-comparisons/LukasiewiczLoss.vcl.golden
  vehicle/tests/golden/compile/logic-and-comparisons/ProductLoss.json.golden
  vehicle/tests/golden/compile/logic-and-comparisons/YagerLoss.vcl.golden
  vehicle/tests/golden/compile/mnist-robustness/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/mnist-robustness/VehicleLoss.vcl.golden
  vehicle/tests/golden/compile/monotonicity/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/reachability/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-constantInput/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-fourierMotzkin/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-gaussianElim/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-pruneDecls/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-quantifier/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-triviallyTrue/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/windController/DL2Loss.vcl.golden
Labels: backend:LossFunctions, refactoring

#672 Prevent tests from being run with +release-build
  vehicle/vehicle.cabal
Labels: build-system, CI

#675 Improved typing error message infrastructure and constraint origin information
  vehicle/src/Vehicle/Backend/JSON.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Normalise/Builtin.hs
  vehicle/src/Vehicle/Compile/Prelude/MonadContext.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/Core.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/IndexSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/UnificationSolver.hs
  vehicle/src/Vehicle/Compile/Type/Core.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/InputOutputInsertion.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Linearity.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Linearity/LinearitySolver.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Polarity.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Polarity/PolaritySolver.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Interface.hs
Labels: refactoring, compiler:type-checker

#677 Fix bug where map wasn't evaluating properly
  ChangeLog.md
  vehicle/src/Vehicle/Compile/Normalise/Builtin.hs
  vehicle/tests/golden/compile/issue669/Marabou.err.golden
  vehicle/tests/golden/compile/issue669/Marabou.out.golden
  vehicle/tests/golden/compile/issue669/Marabou.queries/.vcl-cache-index.golden
  vehicle/tests/golden/compile/issue669/Marabou.queries/p.vcl-plan.golden
  vehicle/tests/golden/compile/issue669/spec.vcl
  vehicle/tests/golden/compile/issue669/test.json
Labels: bug, backend:Marabou

#682 Remove TypeClassSolver class entirely
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/InstanceBuiltins.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Type.hs
  vehicle/tests/golden/compile/simple-fourierMotzkin/Explicit.vcl.golden
  vehicle/tests/golden/error/other-verifier/quantifiedInt/Marabou.err.golden
  vehicle/tests/golden/error/other-verifier/quantifiedNat/Marabou.err.golden
  vehicle/tests/golden/error/other-verifier/quantifiedVectorNat/Marabou.err.golden
  vehicle/tests/golden/error/typing/incorrectTensorLength/TypeCheck.err.golden
  vehicle/tests/golden/error/typing/intAsNat/TypeCheck.err.golden
  vehicle/vehicle.cabal
Labels: refactoring, compiler:type-checker

#686 Implement unification of lambdas
  ChangeLog.md
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/UnificationSolver.hs
  vehicle/src/Vehicle/Compile/Type/Core.hs
  vehicle/tests/golden/compile/issue685/spec.vcl
  vehicle/tests/golden/compile/issue685/test.json
Labels: bug, compiler:type-checker

#687 Refactor some Haskell module locations
  vehicle-syntax/src/Vehicle/Syntax/AST/Instances/NoThunks.hs
  vehicle/app/NewTest.hs
  vehicle/src/Vehicle/Backend/Agda/CapitaliseTypeNames.hs
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Backend/Prelude.hs
  vehicle/src/Vehicle/Backend/Queries.hs
  vehicle/src/Vehicle/Backend/Queries/Error.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Linearity.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Linearity/AnnotationRestrictions.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Linearity/Core.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Linearity/LinearitySolver.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Linearity/Type.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Polarity.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Polarity/AnnotationRestrictions.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Polarity/Core.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Polarity/PolaritySolver.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Polarity/Type.hs
  vehicle/src/Vehicle/Backend/Queries/FourierMotzkinElimination.hs
  vehicle/src/Vehicle/Backend/Queries/GaussianElimination.hs
  vehicle/src/Vehicle/Backend/Queries/IfElimination.hs
  vehicle/src/Vehicle/Backend/Queries/LinearExpr.hs
  vehicle/src/Vehicle/Backend/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Backend/Queries/QuerySetStructure.hs
  vehicle/src/Vehicle/Backend/Queries/UserVariableElimination.hs
  vehicle/src/Vehicle/Backend/Queries/Variable.hs
  vehicle/src/Vehicle/Backend/Queries/VariableReconstruction.hs
  vehicle/src/Vehicle/CommandLine.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/Core.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/InstanceBuiltins.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/InstanceDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Patterns.hs
  vehicle/src/Vehicle/Compile/Warning.hs
  vehicle/src/Vehicle/TypeCheck.hs
  vehicle/src/Vehicle/Verify.hs
  vehicle/src/Vehicle/Verify/Core.hs
  vehicle/src/Vehicle/Verify/QueryFormat.hs
  vehicle/src/Vehicle/Verify/QueryFormat/Core.hs
  vehicle/src/Vehicle/Verify/QueryFormat/Marabou.hs
  vehicle/src/Vehicle/Verify/QueryFormat/VNNLib.hs
  vehicle/src/Vehicle/Verify/Specification/IO.hs
  vehicle/src/Vehicle/Verify/Specification/Status.hs
  vehicle/src/Vehicle/Verify/Verifier.hs
  vehicle/src/Vehicle/Verify/Verifier/Core.hs
  vehicle/src/Vehicle/Verify/Verifier/Marabou.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/CommandLine.hs
  vehicle/vehicle.cabal
Labels: refactoring

#696 Refactor translation to Agda to rely less on pattern synonyms
  CONTRIBUTING.md
  ChangeLog.md
  tasty-golden-executable/src/Test/Tasty/Golden/Executable/Error.hs
  tasty-golden-executable/src/Test/Tasty/Golden/Executable/Runner.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Arg.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Visibility.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/Internal.hs
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Backend/JSON.hs
  vehicle/src/Vehicle/Backend/LossFunction/TypeSystem.hs
  vehicle/src/Vehicle/Backend/Queries.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Linearity/AnnotationRestrictions.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Polarity/PolaritySolver.hs
  vehicle/src/Vehicle/Backend/Queries/IfElimination.hs
  vehicle/src/Vehicle/Backend/Queries/LinearExpr.hs
  vehicle/src/Vehicle/Backend/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Backend/Queries/QuerySetStructure.hs
  vehicle/src/Vehicle/Backend/Queries/UserVariableElimination.hs
  vehicle/src/Vehicle/Backend/Queries/Variable.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/FunctionaliseResources.hs
  vehicle/src/Vehicle/Compile/Normalise/Builtin.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/InputOutputInsertion.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/InstanceDefaults.hs
  vehicle/src/Vehicle/Expr/BuiltinInterface.hs
  vehicle/src/Vehicle/Expr/BuiltinPatterns.hs
  vehicle/src/Vehicle/Verify/Specification/Status.hs
  vehicle/tests/golden/compile/andGate/test.json
  vehicle/tests/golden/compile/autoencoderError/test.json
  vehicle/tests/golden/compile/dogsHierarchy/test.json
  vehicle/tests/golden/compile/monotonicity/test.json
  vehicle/tests/golden/compile/reachability/test.json
  vehicle/tests/golden/compile/simple-constantInput/test.json
  vehicle/tests/golden/compile/simple-if/test.json
  vehicle/tests/golden/compile/simple-pruneDecls/test.json
  vehicle/tests/golden/compile/simple-quantifier/test.json
  vehicle/tests/golden/compile/simple-triviallyTrue/test.json
  vehicle/tests/golden/compile/simple-vector/test.json
  vehicle/tests/golden/compile/windController/test.json
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/Normalisation.hs
Labels: backend:Agda, refactoring

#698 Remove higher order declarations before exporting to JSON
  vehicle-syntax/src/Vehicle/Syntax/AST/Binder.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle/lib/std.vcl
  vehicle/src/Vehicle/Backend/Tensors/Clean.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/tests/golden/compile/acasXu/Explicit.vcl.golden
  vehicle/tests/golden/compile/andGate/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/andGate/Explicit.vcl.golden
  vehicle/tests/golden/compile/autoencoderError/Explicit.vcl.golden
  vehicle/tests/golden/compile/bounded/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/bounded/Explicit.vcl.golden
  vehicle/tests/golden/compile/dogsHierarchy/Explicit.vcl.golden
  vehicle/tests/golden/compile/increasing/Explicit.vcl.golden
  vehicle/tests/golden/compile/logic-and-comparisons/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/logic-and-comparisons/Explicit.vcl.golden
  vehicle/tests/golden/compile/logic-and-comparisons/GodelLoss.vcl.golden
  vehicle/tests/golden/compile/logic-and-comparisons/LukasiewiczLoss.vcl.golden
  vehicle/tests/golden/compile/logic-and-comparisons/ProductLoss.json.golden
  vehicle/tests/golden/compile/logic-and-comparisons/YagerLoss.vcl.golden
  vehicle/tests/golden/compile/mnist-robustness/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/mnist-robustness/Explicit.vcl.golden
  vehicle/tests/golden/compile/mnist-robustness/VehicleLoss.vcl.golden
  vehicle/tests/golden/compile/monotonicity/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/monotonicity/Explicit.vcl.golden
  vehicle/tests/golden/compile/reachability/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/reachability/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-constantInput/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-constantInput/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-constantNetworkInput/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-foreach/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-foreach/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-fourierMotzkin/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-fourierMotzkin/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-gaussianElim/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-gaussianElim/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-if/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-let/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-quantifierIn/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-tensor/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-triviallyTrue/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-triviallyTrue/Explicit.vcl.golden
  vehicle/tests/golden/compile/simple-vector/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/simple-vector/Explicit.vcl.golden
  vehicle/tests/golden/compile/windController/DL2Loss.vcl.golden
  vehicle/tests/golden/compile/windController/Explicit.vcl.golden
  vehicle/vehicle.cabal
Labels: enhancement, backend:LossFunctions

#703 Fix couple of bugs in docs
  docs/dev/verifiers.md
  docs/exporting.rst
Labels: bug, documentation

#704 Use kebab-case in command line docs
  ChangeLog.md
  docs/exporting.rst
  docs/verifying.rst
  examples/windController/README.md
  vehicle-python/src/vehicle_lang/verify/__init__.py
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/CommandLine.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Export.hs
  vehicle/src/Vehicle/Verify.hs
  vehicle/tests/golden/compile/help/compile.out.golden
  vehicle/tests/golden/compile/help/export.out.golden
  vehicle/tests/golden/compile/help/verify.out.golden
  vehicle/tests/golden/error/argument/missingVerifier/test.json
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/CommandLine.hs
Labels: refactoring, UX

#708 Move `Ann` from expressions to builtins
  vehicle-syntax/src/Vehicle/Syntax/AST/Expr.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/Internal.hs
  vehicle-syntax/src/Vehicle/Syntax/Builtin.hs
  vehicle/src/Vehicle/Backend/Agda/CapitaliseTypeNames.hs
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Backend/JSON.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Linearity/Type.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Polarity/Type.hs
  vehicle/src/Vehicle/Backend/Queries/QuerySetStructure.hs
  vehicle/src/Vehicle/Backend/Tensors/Clean.hs
  vehicle/src/Vehicle/Compile/Dependency.hs
  vehicle/src/Vehicle/Compile/Descope.hs
  vehicle/src/Vehicle/Compile/Normalise/Builtin.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Prelude/Utils.hs
  vehicle/src/Vehicle/Compile/Scope.hs
  vehicle/src/Vehicle/Compile/Simplify.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Irrelevance.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Type.hs
  vehicle/src/Vehicle/Expr/BuiltinInterface.hs
  vehicle/src/Vehicle/Expr/DeBruijn.hs
Labels: refactoring, compiler:type-checker

#709 Remove meta-substitution from `MonadNorm`
  vehicle/src/Vehicle/Backend/Queries/Error/Linearity/LinearitySolver.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Polarity/PolaritySolver.hs
  vehicle/src/Vehicle/Compile/Normalise/Monad.hs
  vehicle/src/Vehicle/Compile/Type.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/IndexSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceDefaultSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/UnificationSolver.hs
  vehicle/src/Vehicle/Compile/Type/Force.hs
  vehicle/src/Vehicle/Compile/Type/Generalise.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Substitution.hs
  vehicle/src/Vehicle/Compile/Type/Monad.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Instance.hs
Labels: refactoring, compiler:normalisation

#710 Remove `ConsVector` builtin
  vehicle-python/src/vehicle_lang/ast/__init__.py
  vehicle-python/src/vehicle_lang/compile/abc.py
  vehicle-python/src/vehicle_lang/compile/python.py
  vehicle-python/src/vehicle_lang/compile/tensorflow.py
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Utils.hs
  vehicle-syntax/src/Vehicle/Syntax/Builtin.hs
  vehicle-syntax/src/Vehicle/Syntax/External.cf
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Backend/JSON.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Linearity/Type.hs
  vehicle/src/Vehicle/Backend/Queries/Error/Polarity/Type.hs
  vehicle/src/Vehicle/Compile/Normalise/Builtin.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Type.hs
Labels: refactoring

#711 Add warnings for conversion from strict to non-strict inequalities
  ChangeLog.md
  vehicle/src/Vehicle/Backend/Queries.hs
  vehicle/src/Vehicle/Compile/Prelude/MonadContext.hs
  vehicle/src/Vehicle/Compile/Warning.hs
  vehicle/src/Vehicle/Verify/Core.hs
  vehicle/src/Vehicle/Verify/QueryFormat/Core.hs
  vehicle/src/Vehicle/Verify/QueryFormat/Marabou.hs
  vehicle/tests/golden/compile/acasXu/Marabou.err.golden
  vehicle/tests/golden/compile/andGate/Marabou.err.golden
  vehicle/tests/golden/compile/autoencoderError/Marabou.err.golden
  vehicle/tests/golden/compile/bounded/Marabou.err.golden
  vehicle/tests/golden/compile/increasing/Marabou.err.golden
  vehicle/tests/golden/compile/issue551/Marabou.err.golden
  vehicle/tests/golden/compile/issue615/Marabou.err.golden
  vehicle/tests/golden/compile/monotonicity/Marabou.err.golden
  vehicle/tests/golden/compile/simple-constantInput/Marabou.err.golden
  vehicle/tests/golden/compile/simple-if/Marabou.err.golden
  vehicle/tests/golden/compile/simple-pruneDecls/Marabou.err.golden
  vehicle/tests/golden/compile/simple-quantifier/Marabou.err.golden
  vehicle/tests/golden/warning/trivial/Marabou.queries/multiProperty!1!0-query1.txt.golden
  vehicle/tests/golden/warning/trivial/test.json
Labels: compiler:error-messages, UX

#713 Fix compilation of abstract index equalities
  ChangeLog.md
  vehicle/src/Vehicle/Backend/Queries/QuerySetStructure.hs
  vehicle/tests/golden/compile/issue712/Marabou.queries/isMalcious-query1.txt.golden
  vehicle/tests/golden/compile/issue712/Marabou.queries/isMalcious.vcl-plan.golden
  vehicle/tests/golden/compile/issue712/fake.onnx
  vehicle/tests/golden/compile/issue712/spec.vcl
  vehicle/tests/golden/compile/issue712/test.json
Labels: bug, backend:Marabou

#716 Split MonadContext into MonadFreeContext and MonadBoundContext
  vehicle-syntax/src/Vehicle/Syntax/AST/Binder.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Delaborate/Internal.hs
  vehicle/src/Vehicle/Backend/Agda/CapitaliseTypeNames.hs
  vehicle/src/Vehicle/Backend/JSON.hs
  vehicle/src/Vehicle/Backend/Queries.hs
  vehicle/src/Vehicle/Backend/Queries/GaussianElimination.hs
  vehicle/src/Vehicle/Backend/Queries/LinearExpr.hs
  vehicle/src/Vehicle/Backend/Queries/NetworkElimination.hs
  vehicle/src/Vehicle/Backend/Queries/QuerySetStructure.hs
  vehicle/src/Vehicle/Backend/Queries/UserVariableElimination.hs
  vehicle/src/Vehicle/Backend/Queries/Variable.hs
  vehicle/src/Vehicle/Backend/Tensors/Clean.hs
  vehicle/src/Vehicle/Compile/Context/Bound.hs
  vehicle/src/Vehicle/Compile/Context/Bound/Class.hs
  vehicle/src/Vehicle/Compile/Context/Bound/Core.hs
  vehicle/src/Vehicle/Compile/Context/Bound/Instance.hs
  vehicle/src/Vehicle/Compile/Context/Free.hs
  vehicle/src/Vehicle/Compile/Context/Free/Class.hs
  vehicle/src/Vehicle/Compile/Context/Free/Core.hs
  vehicle/src/Vehicle/Compile/Context/Free/Instance.hs
  vehicle/src/Vehicle/Compile/Context/Var.hs
  vehicle/src/Vehicle/Compile/Descope.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/EtaConversion.hs
  vehicle/src/Vehicle/Compile/ExpandResources.hs
  vehicle/src/Vehicle/Compile/FunctionaliseResources.hs
  vehicle/src/Vehicle/Compile/Monomorphisation.hs
  vehicle/src/Vehicle/Compile/Normalise/Monad.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Normalise/Quote.hs
  vehicle/src/Vehicle/Compile/Prelude.hs
  vehicle/src/Vehicle/Compile/Prelude/Contexts.hs
  vehicle/src/Vehicle/Compile/Prelude/MonadContext.hs
  vehicle/src/Vehicle/Compile/Prelude/Utils.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Type/Bidirectional.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/InstanceSolver.hs
  vehicle/src/Vehicle/Compile/Type/Constraint/UnificationSolver.hs
  vehicle/src/Vehicle/Compile/Type/Core.hs
  vehicle/src/Vehicle/Compile/Type/Meta/Variable.hs
  vehicle/src/Vehicle/Compile/Type/Monad.hs
  vehicle/src/Vehicle/Compile/Type/Monad/Class.hs
  vehicle/src/Vehicle/Expr/DeBruijn.hs
  vehicle/src/Vehicle/Expr/Normalised.hs
  vehicle/src/Vehicle/TypeCheck.hs
  vehicle/src/Vehicle/Verify/Specification/Status.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/Normalisation.hs
  vehicle/vehicle.cabal
Labels: refactoring, compiler:other
