Repository vehicle-lang/vehicle, pull requests merged in 2023-04, with the labels that each got.

#490 Cache the results of Gaussian elimination to avoid re-solving the same equations repeatedly
  vehicle/src/Vehicle/Compile/Queries.hs
  vehicle/src/Vehicle/Compile/Queries/FourierMotzkinElimination.hs
  vehicle/src/Vehicle/Compile/Queries/GaussianElimination.hs
  vehicle/src/Vehicle/Compile/Queries/LinearExpr.hs
  vehicle/src/Vehicle/Compile/Queries/LinearSatisfactionProblem.hs
  vehicle/src/Vehicle/Prelude/Supply.hs
Labels: enhancement, performance

#494 Overload division so that dividing two `Nat`s make a `Rat`
  ChangeLog.md
  docs-source/language/arithmetic.rst
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin.hs
  vehicle-syntax/src/Vehicle/Syntax/AST/Builtin/TypeClass.hs
  vehicle-syntax/src/Vehicle/Syntax/BNFC/Elaborate/External.hs
  vehicle-syntax/src/Vehicle/Syntax/External.cf
  vehicle/src/Vehicle/Backend/Agda/Compile.hs
  vehicle/src/Vehicle/Compile/Error.hs
  vehicle/src/Vehicle/Compile/Error/Message.hs
  vehicle/src/Vehicle/Compile/Normalise/NBE.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/InstanceBuiltins.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/TypeClassDefaults.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Constraint/TypeClassSolver.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Patterns.hs
  vehicle/src/Vehicle/Compile/Type/Subsystem/Standard/Type.hs
  vehicle/src/Vehicle/Expr/DSL.hs
  vehicle/tests/golden/compile/simple-arithmetic/Agda.agda.golden
  vehicle/tests/golden/compile/simple-arithmetic/Marabou.err.golden
  vehicle/tests/golden/compile/simple-arithmetic/Marabou.out.golden
  vehicle/tests/golden/compile/simple-arithmetic/Marabou.queries/.vcl-plan.golden
  vehicle/tests/golden/compile/simple-arithmetic/Marabou.queries/property-query1.txt.golden
  vehicle/tests/golden/compile/simple-arithmetic/fake.onnx
  vehicle/tests/golden/compile/simple-arithmetic/spec.vcl
  vehicle/tests/golden/compile/simple-arithmetic/test.json
  vehicle/tests/golden/compile/simple-let/Agda.agda.golden
Labels: enhancement, language

#475 Build Marabou on CI
  .github/actions/setup-marabou/action.yml
  .github/workflows/ci.yml
  .github/workflows/test-marabou-integration.yml
Labels: enhancement, CI

#508 Added three ACASXu networks to example folder
  examples/acasXu/README.md
  examples/acasXu/acasXu.vcl
  examples/acasXu/acasXu_1_7.onnx
  examples/acasXu/acasXu_1_8.onnx
  examples/acasXu/acasXu_1_9.onnx
  vehicle/src/Vehicle/Verify/Specification/Status.hs
  vehicle/src/Vehicle/Verify/Verifier/Marabou.hs
  vehicle/tests/golden/compile/acasXu/Agda.agda.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/.vcl-plan.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property1-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property10-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property10-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property10-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property10-query4.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property2-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property3-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property4-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property5-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property5-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property5-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property5-query4.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query4.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query5.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query6.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query7.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property6-query8.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property7-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property7-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query10.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query11.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query12.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query13.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query14.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query15.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query16.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query4.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query5.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query6.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query7.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query8.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property8-query9.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property9-query1.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property9-query2.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property9-query3.txt.golden
  vehicle/tests/golden/compile/acasXu/Marabou.queries/property9-query4.txt.golden
Labels: documentation, enhancement

#518 Use file-embed to embed standard library
  vehicle/lib/std.vcl
  vehicle/src/Vehicle/Libraries/StandardLibrary.hs
  vehicle/vehicle.cabal
Labels: enhancement
