Repository vehicle-lang/vehicle, pull requests merged in 2025-09, with the labels that each got.

#949 List resources does not list inferable parameters
  ChangeLog.md
  vehicle-syntax/src/Vehicle/Syntax/AST/Decl.hs
  vehicle/src/Vehicle/List.hs
  vehicle/tests/golden/compile/mnist-robustness/ListResources.out.golden
Labels: compiler:other

#947 fix(vehicle-python): make Setup.hs more robust against Cabal versions
  vehicle-python/Setup.hs
Labels: build-system

#959 Refactor Bounds and Assertion to be more general
  vehicle/src/Vehicle/Backend/LossFunction/Domain.hs
  vehicle/src/Vehicle/Backend/Queries/ConstraintSearch.hs
  vehicle/src/Vehicle/Backend/Queries/MetaNetworkCalculation.hs
  vehicle/src/Vehicle/Backend/Queries/PostProcessing.hs
  vehicle/src/Vehicle/Backend/Queries/UserVariableElimination.hs
  vehicle/src/Vehicle/Backend/Queries/UserVariableElimination/Core.hs
  vehicle/src/Vehicle/Backend/Queries/UserVariableElimination/EliminateExists.hs
  vehicle/src/Vehicle/Backend/Queries/UserVariableElimination/VariableReconstruction.hs
  vehicle/src/Vehicle/Compile/FourierMotzkinElimination.hs
  vehicle/src/Vehicle/Compile/Print.hs
  vehicle/src/Vehicle/Compile/Rational/LinearExpr.hs
  vehicle/src/Vehicle/Data/Assertion.hs
  vehicle/src/Vehicle/Data/Code/LinearExpr.hs
  vehicle/src/Vehicle/Data/QuantifiedVariable.hs
  vehicle/src/Vehicle/Verify/Specification.hs
Labels: compiler:verifier-backend, compiler:loss-backend
