Repository vehicle-lang/vehicle, pull requests merged in 2025-08, with the labels that each got.

#923 Fix compatibility problems up to GHC 9.12
  README.md
  tasty-golden-executable/src/Test/Tasty/Golden/Executable/TestSpec/Accept.hs
  tasty-golden-executable/src/Test/Tasty/Golden/Executable/TestSpec/External.hs
  tasty-golden-executable/src/Test/Tasty/Golden/Executable/TestSpec/FilePattern.hs
  tasty-golden-executable/src/Test/Tasty/Golden/Executable/TestSpec/Ignore.hs
  tasty-golden-executable/src/Test/Tasty/Golden/Executable/TestSpec/SizeOnly.hs
  tasty-golden-executable/src/Test/Tasty/Golden/Executable/TestSpec/TextPattern.hs
  tasty-golden-executable/src/Test/Tasty/Golden/Executable/TestSpec/Timeout.hs
  tasty-golden-executable/tasty-golden-executable.cabal
  vehicle-syntax/src/Vehicle/Syntax/AST/Provenance.hs
  vehicle-syntax/src/Vehicle/Syntax/Prelude.hs
  vehicle-syntax/vehicle-syntax.cabal
  vehicle/src/Vehicle/Backend/LossFunction/Domain.hs
  vehicle/src/Vehicle/Backend/Queries/MetaNetworkCalculation.hs
  vehicle/src/Vehicle/Backend/Queries/PostProcessing.hs
  vehicle/src/Vehicle/Prelude/Misc.hs
Labels: refactoring

#931 Fix bug in evaluation of folds over multi-dimensional tensors
  ChangeLog.md
  vehicle/src/Vehicle/Backend/Queries/Unblock.hs
  vehicle/src/Vehicle/Backend/Queries/UserVariableElimination.hs
  vehicle/src/Vehicle/Data/Builtin/Interface/Blocked.hs
  vehicle/src/Vehicle/Data/Builtin/Interface/Normalise.hs
  vehicle/tests/golden/compile/issue928/Marabou.err.golden
  vehicle/tests/golden/compile/issue928/Marabou.queries/robust-query1.txt.golden
  vehicle/tests/golden/compile/issue928/Marabou.queries/robust.vcl-plan.golden
  vehicle/tests/golden/compile/issue928/baseline.onnx
  vehicle/tests/golden/compile/issue928/spec.vcl
  vehicle/tests/golden/compile/issue928/test.json
Labels: bug, backend:verifiers

#927 Global `--json` option
  ChangeLog.md
  vehicle/src/Vehicle.hs
  vehicle/src/Vehicle/CommandLine.hs
  vehicle/src/Vehicle/Compile.hs
  vehicle/src/Vehicle/Export.hs
  vehicle/src/Vehicle/List.hs
  vehicle/src/Vehicle/Prelude/Logging/Instance.hs
  vehicle/src/Vehicle/TypeCheck.hs
  vehicle/src/Vehicle/Validate.hs
  vehicle/src/Vehicle/Verify.hs
  vehicle/tests/unit/Vehicle/Test/Unit/Compile/CommandLine.hs
Labels: enhancement
